import { lmcPipeSizeOptions } from "../config/lmc-fields";
import type {
  BillingCompletionStatus,
  CommissioningConversionDetails,
  CustomerConnectionDetails,
  CustomerFormValues,
  CustomerSurvey,
  FittingsAccessories,
  GiMeasurements,
  LmcPipeSize,
  LmcPipeSizeRecord,
  LmcPipelineWork,
  MdpeFittings,
  ValvesRegulators,
} from "../types/customer.types";

export const emptyGiMeasurements: GiMeasurements = {
  tfToRegulator: "",
  inlet: "",
  outlet: "",
  totalGiPipeHalfInch: "",
  giPipeThreeQuarterInch: "",
  giPipeOneInch: "",
  giPipeOneAndHalfInch: "",
  giPipeTwoInch: "",
  approvalStatus: "draft",
  approvalComments: "",
};

export const emptyValvesRegulators: ValvesRegulators = {
  isolationValveHalfInch: "",
  isolationValveThreeQuarterInch: "",
  isolationValveOneInch: "",
  isolationValveOneAndHalfInch: "",
  isolationValveTwoInch: "",
  applianceValveHalfInch: "",
  regulator6BarTo100Mbar: "",
  regulator6BarTo21Mbar: "",
  regulator100MbarTo21Mbar: "",
  warningPlate: "",
};

export const emptyFittingsAccessories: FittingsAccessories = {
  clampHalfInch: "",
  clamp3InchToHalfInch: "",
  elbowHalfInch: "",
  mfElbowHalfInch: "",
  socketHalfInch: "",
  teeHalfInch: "",
  nipple2Inch: "",
  nipple3Inch: "",
  nipple4Inch: "",
  reducerElbowThreeQuarterToHalfInch: "",
  threeQuarterInchTo3Inch: "",
  unionHalfInch: "",
  plugHalfInch: "",
  fittingsOneAndHalfInchQuantity: "",
  fittingsTwoInchQuantity: "",
  extraGiAbove10Metres: "",
};

export const emptyCustomerConnection: CustomerConnectionDetails = {
  reportNoGi: "",
  reportNoGc: "",
  reportNoConversion: "",
  trBpNo: "",
  mobileNo: "",
  customerName: "",
  fullAddress: "",
  scheme: "",
  plumberId: "",
  plumberName: "",
  jobCardDone: "",
  connectionType: "Domestic",
  houseType: "",
};

export const emptyCustomerSurvey: CustomerSurvey = {
  id: "survey-draft",
  surveyId: "",
  surveyDate: "",
  assignedSurveyor: "",
  submittedBy: "",
  submissionDate: "",
  latitude: 0,
  longitude: 0,
  captureAccuracy: "",
  workableStatus: "Workable",
  approvalStatus: "Draft",
  initialMeasurements: "",
  siteAccessibility: "Pending",
  meterPlacement: "Pending",
  pipelineRoute: "Pending",
  civilWorkRequired: "No",
  obstaclesRemarks: "",
  notes: "",
  reason: "",
  recommendedAction: "",
  expectedResolutionDate: "",
  approvalComments: "",
  evidence: [],
  revisions: [],
};

export function emptyPipeSizeRecord(pipeSize: LmcPipeSize): LmcPipeSizeRecord {
  return {
    id: `pipe-${pipeSize.toLowerCase().replace(/\s+/g, "-")}`,
    pipeSize,
    lengthMetres: "",
    layingDate: "",
    testingDate: "",
    purgingDate: "",
    layingStatus: "Not Started",
    testingStatus: "Not Started",
    purgingStatus: "Not Started",
    jointFittingDetails: "",
    remarks: "",
    evidence: [],
  };
}

export const emptyLmcPipelineWork: LmcPipelineWork = {
  pipeRecords: lmcPipeSizeOptions.map((size) => emptyPipeSizeRecord(size)),
  fourMetresUnderGc: "",
  fourMetresAboveGc: "",
  tfHalfInch: "",
  tfOneInch: "",
  pcc: "",
  rccNalaCrossing: "",
  paverBlocks: "",
  malua: "",
  hardRock: "",
  approvalStatus: "draft",
  approvalComments: "",
};

export const emptyMdpeFittings: MdpeFittings = {
  saddle90To32Mm: "",
  saddle90Mm: "",
  saddle63To32Mm: "",
  saddle32To20Mm: "",
  tee90Mm: "",
  tee32Mm: "",
  tee20Mm: "",
  reducerCoupler90To63Mm: "",
  reducerCoupler63To32Mm: "",
  reducerCoupler32To20Mm: "",
  coupler90Mm: "",
  coupler32Mm: "",
  coupler20Mm: "",
  endCap90Mm: "",
};

export const emptyCommissioningConversion: CommissioningConversionDetails = {
  meterNo: "",
  installationDate: "",
  commissioningDate: "",
  conversionDate: "",
  regulatorPressure: "",
  regulatorNo: "",
  meterType: "",
  meterReading: "",
  nonConversionRemark: "",
  approvalStatus: "draft",
  approvalComments: "",
};

export const emptyBillingCompletion: BillingCompletionStatus = {
  paymentStatus: "Pending",
  paymentMode: "",
  initialAmount: "",
  jmrDone: false,
  jmrSubmittedInPbg: false,
  giBillDone: false,
  gcBillDone: false,
  conversionBillDone: false,
  remark: "",
};

export const defaultCustomerFormValues: CustomerFormValues = {
  status: "Draft",
  projectId: "",
  siteId: "",
  projectName: "",
  siteArea: "",
  city: "",
  customerConnection: emptyCustomerConnection,
  giMeasurements: emptyGiMeasurements,
  valvesRegulators: emptyValvesRegulators,
  fittingsAccessories: emptyFittingsAccessories,
  lmcPipelineWork: emptyLmcPipelineWork,
  mdpeFittings: emptyMdpeFittings,
  commissioningConversion: emptyCommissioningConversion,
  billingCompletion: emptyBillingCompletion,
  survey: undefined,
  media: [],
  documents: [],
  customFields: {},
};
