import type {
  SubmissionStatus,
  Survey,
  SurveyActivity,
  SurveyPhoto,
  SurveyRevision,
  WorkableStatus,
} from "../types/survey.types";

export const workableStatusOptions: WorkableStatus[] = [
  "Workable",
  "Partially Workable",
  "Not Workable",
];

export const submissionStatusOptions: SubmissionStatus[] = [
  "Draft",
  "Submitted",
  "In Review",
  "Approved",
  "Sent Back",
  "Rejected",
];

export const surveys: Survey[] = [
  {
    id: "survey-001",
    surveyId: "SUR-100245",
    customerId: "cust-001",
    customerName: "Rajesh Kumar",
    mobileNumber: "9876543210",
    bpTrNumber: "BP-100245",
    projectId: "shyam-nagar-cgd",
    projectName: "Shyam Nagar CGD Project",
    siteArea: "Shyam Nagar Block A",
    supervisor: "Ramesh Kumar",
    submittedBy: "Vikas Saini",
    surveyDate: "2025-01-28",
    submissionDate: "2025-01-28 16:40",
    workableStatus: "Workable",
    submissionStatus: "Submitted",
    fullAddress: "42, Shyam Nagar Block A, Jaipur",
    latitude: 26.8951,
    longitude: 75.7684,
    captureAccuracy: "8 m",
    houseType: "Independent House",
    connectionType: "Domestic",
    siteAccessibility: "Approved",
    meterPlacement: "Workable",
    pipelineRoute: "Workable",
    civilWorkRequired: "No",
    obstructionDetails: "No obstruction found.",
    notes: "Customer available after 10 AM. Meter can be placed on front wall.",
    reason: "",
    recommendedAction: "Proceed for GI planning.",
    expectedResolutionDate: "",
    remarks: "Site is ready for next stage.",
    approvalComments: "Pending supervisor approval.",
    photoCount: 4,
  },
  {
    id: "survey-002",
    surveyId: "SUR-553901",
    customerId: "cust-002",
    customerName: "Meena Sharma",
    mobileNumber: "9823411122",
    bpTrNumber: "TR-553901",
    projectId: "shyam-nagar-cgd",
    projectName: "Shyam Nagar CGD Project",
    siteArea: "Shyam Nagar Block B",
    supervisor: "Kavita Joshi",
    submittedBy: "Amit Rathore",
    surveyDate: "2025-02-04",
    submissionDate: "2025-02-04 12:15",
    workableStatus: "Partially Workable",
    submissionStatus: "Sent Back",
    fullAddress: "11, New Sanganer Road, Shyam Nagar, Jaipur",
    latitude: 26.8877,
    longitude: 75.7592,
    captureAccuracy: "12 m",
    houseType: "Apartment",
    connectionType: "Domestic",
    siteAccessibility: "Approved",
    meterPlacement: "Partially Workable",
    pipelineRoute: "Partially Workable",
    civilWorkRequired: "Yes",
    obstructionDetails: "Meter wall needs minor civil clearance.",
    notes: "Society guard approval required for work entry.",
    reason: "Meter placement needs confirmation.",
    recommendedAction: "Revisit with supervisor.",
    expectedResolutionDate: "2025-02-09",
    remarks: "Sent back for clearer meter photo.",
    approvalComments: "Upload obstruction photo and revised meter placement.",
    photoCount: 3,
  },
  {
    id: "survey-003",
    surveyId: "SUR-220118",
    customerId: "cust-003",
    customerName: "Green Mart Store",
    mobileNumber: "9810012200",
    bpTrNumber: "BP-220118",
    projectId: "green-city-phase-1",
    projectName: "Green City Phase 1",
    siteArea: "Commercial Block",
    supervisor: "Neha Verma",
    submittedBy: "Pawan Jain",
    surveyDate: "2025-02-13",
    submissionDate: "2025-02-13 17:30",
    workableStatus: "Workable",
    submissionStatus: "Approved",
    fullAddress: "Shop 8, Green City Phase 1, Indore",
    latitude: 22.7196,
    longitude: 75.8577,
    captureAccuracy: "6 m",
    houseType: "Retail Shop",
    connectionType: "Commercial",
    siteAccessibility: "Approved",
    meterPlacement: "Workable",
    pipelineRoute: "Workable",
    civilWorkRequired: "No",
    obstructionDetails: "No obstruction.",
    notes: "Commercial meter location marked near back entry.",
    reason: "",
    recommendedAction: "Proceed to installation.",
    expectedResolutionDate: "",
    remarks: "Approved for GI and GC stages.",
    approvalComments: "Good to proceed.",
    photoCount: 5,
  },
  {
    id: "survey-004",
    surveyId: "SUR-783441",
    customerId: "cust-004",
    customerName: "Rafiq Khan",
    mobileNumber: "9901122334",
    bpTrNumber: "TR-783441",
    projectId: "sunrise-enclave-cgd",
    projectName: "Sunrise Enclave CGD",
    siteArea: "Sunrise Enclave",
    supervisor: "Priya Nair",
    submittedBy: "Sameer Ali",
    surveyDate: "2025-03-04",
    submissionDate: "",
    workableStatus: "Not Workable",
    submissionStatus: "Draft",
    fullAddress: "7, Sunrise Enclave, Udaipur",
    latitude: 24.5854,
    longitude: 73.7125,
    captureAccuracy: "15 m",
    houseType: "Villa",
    connectionType: "Domestic",
    siteAccessibility: "Rejected",
    meterPlacement: "Not Workable",
    pipelineRoute: "Not Workable",
    civilWorkRequired: "Yes",
    obstructionDetails: "Boundary wall blocks proposed route.",
    notes: "Need alternate route after customer confirmation.",
    reason: "Pipeline route blocked.",
    recommendedAction: "Plan alternate route.",
    expectedResolutionDate: "2025-03-12",
    remarks: "Draft saved by field team.",
    approvalComments: "",
    photoCount: 2,
  },
];

export const surveyPhotos: SurveyPhoto[] = [
  {
    id: "photo-1",
    label: "Site front photo",
    caption: "Front elevation with meter approach.",
    fileName: "site_front_bp_100245.jpg",
  },
  {
    id: "photo-2",
    label: "Meter location photo",
    caption: "Marked meter point near front wall.",
    fileName: "meter_location_bp_100245.jpg",
  },
  {
    id: "photo-3",
    label: "Pipeline route photo",
    caption: "Route is clear from riser to kitchen wall.",
    fileName: "pipeline_route_bp_100245.jpg",
  },
  {
    id: "photo-4",
    label: "Obstruction photo",
    caption: "No obstruction captured.",
    fileName: "obstruction_bp_100245.jpg",
  },
];

export const surveyActivity: SurveyActivity[] = [
  {
    id: "activity-1",
    title: "Survey created",
    actor: "Vikas Saini",
    dateTime: "2025-01-28 10:20",
    description: "Survey draft was created from field visit.",
  },
  {
    id: "activity-2",
    title: "Photos uploaded",
    actor: "Vikas Saini",
    dateTime: "2025-01-28 15:55",
    description: "Site front, meter location and route photos were added.",
  },
  {
    id: "activity-3",
    title: "Submitted for approval",
    actor: "Vikas Saini",
    dateTime: "2025-01-28 16:40",
    description: "Survey was submitted to supervisor.",
  },
];

export const surveyRevisions: SurveyRevision[] = [
  {
    id: "rev-1",
    revisionNumber: "Revision 1",
    status: "Submitted",
    submittedBy: "Amit Rathore",
    date: "2025-02-04",
    notes: "Initial survey submitted with partial meter placement details.",
  },
  {
    id: "rev-2",
    revisionNumber: "Revision 2",
    status: "Sent Back",
    submittedBy: "Kavita Joshi",
    date: "2025-02-06",
    notes: "Sent back for obstruction photo and revised meter placement.",
  },
];

export function getSurveyById(id: string) {
  return surveys.find((survey) => survey.id === id) ?? surveys[0];
}

export const surveyProjectOptions = Array.from(
  new Map(surveys.map((survey) => [survey.projectId, survey.projectName])),
).map(([value, label]) => ({ value, label }));

export const surveySiteOptions = Array.from(new Set(surveys.map((survey) => survey.siteArea)));
export const surveySupervisorOptions = Array.from(
  new Set(surveys.map((survey) => survey.supervisor)),
);
