import type {
  ActivityItem,
  AssignedUser,
  Project,
  ProjectDocument,
  ProjectSite,
} from "../types/project.types";

export const projectStatusOptions = [
  "Draft",
  "In Progress",
  "Completed",
  "On Hold",
  "Cancelled",
] as const;

export const projects: Project[] = [
  {
    id: "shyam-nagar-cgd",
    name: "Shyam Nagar CGD Project",
    code: "CGD-SN-2025",
    client: "Rajasthan City Gas Distribution Ltd.",
    consultant: "Techno Consult Pvt. Ltd.",
    contractor: "ABC Infra Ltd.",
    projectType: "CGD Network",
    city: "Jaipur",
    area: "Shyam Nagar",
    description:
      "City Gas Distribution project for Shyam Nagar area covering domestic, commercial and industrial connections with MDPE pipeline network.",
    startDate: "2025-01-15",
    plannedEndDate: "2026-01-14",
    status: "In Progress",
    contractValue: "\u20B9 12.50 Cr",
    assignedManager: "Amit Sharma",
  },
  {
    id: "green-city-phase-1",
    name: "Green City Phase 1",
    code: "GCP-01-2024",
    client: "Green City Developers",
    consultant: "Urban Utility Consultants",
    contractor: "Gasline Engineers",
    projectType: "Pipeline Extension",
    city: "Indore",
    area: "Green City Township",
    description: "Pipeline and connection rollout for Green City Phase 1.",
    startDate: "2024-12-10",
    plannedEndDate: "2025-11-30",
    status: "In Progress",
    contractValue: "\u20B9 8.40 Cr",
    assignedManager: "Neha Verma",
  },
  {
    id: "city-gas-network-jaipur",
    name: "City Gas Network - Jaipur",
    code: "CGN-JPR-2024",
    client: "Jaipur Gas Utility",
    consultant: "Infra Design Studio",
    contractor: "MG Construction",
    projectType: "Network Upgrade",
    city: "Jaipur",
    area: "Central Jaipur",
    description: "Network upgrade and customer conversion work across Jaipur.",
    startDate: "2024-11-05",
    plannedEndDate: "2025-12-20",
    status: "In Progress",
    contractValue: "\u20B9 10.20 Cr",
    assignedManager: "Rahul Mehta",
  },
  {
    id: "sunrise-enclave-cgd",
    name: "Sunrise Enclave CGD",
    code: "SEC-2025",
    client: "Sunrise Enclave Welfare Society",
    consultant: "Pipeline Advisory Services",
    contractor: "ABC Infra Ltd.",
    projectType: "Residential CGD",
    city: "Udaipur",
    area: "Sunrise Enclave",
    description: "Residential CGD network and customer onboarding.",
    startDate: "2025-02-20",
    plannedEndDate: "2025-10-30",
    status: "In Progress",
    contractValue: "\u20B9 4.75 Cr",
    assignedManager: "Priya Nair",
  },
  {
    id: "ajmer-city-gas-project",
    name: "Ajmer City Gas Project",
    code: "ACG-2024",
    client: "Ajmer Municipal Gas Board",
    consultant: "Northwest Infra Consultants",
    contractor: "Gasline Engineers",
    projectType: "CGD Network",
    city: "Ajmer",
    area: "Ajmer Urban",
    description: "Completed city gas distribution package for Ajmer.",
    startDate: "2024-08-01",
    plannedEndDate: "2025-06-30",
    status: "Completed",
    contractValue: "\u20B9 9.10 Cr",
    assignedManager: "Devendra Singh",
  },
];

export const projectSites: ProjectSite[] = [
  {
    id: "site-1",
    name: "Shyam Nagar Block A",
    code: "SN-A",
    city: "Jaipur",
    fullAddress: "Shyam Nagar Block A, Jaipur, Rajasthan",
    latitude: 26.8951,
    longitude: 75.7684,
    supervisor: "Ramesh Kumar",
    plannedConnections: 1800,
    startDate: "2025-01-20",
    endDate: "2025-07-30",
    status: "Active",
    remarks: "Main residential block.",
  },
  {
    id: "site-2",
    name: "Shyam Nagar Block B",
    code: "SN-B",
    city: "Jaipur",
    fullAddress: "New Sanganer Road, Shyam Nagar, Jaipur",
    latitude: 26.8877,
    longitude: 75.7592,
    supervisor: "Kavita Joshi",
    plannedConnections: 1450,
    startDate: "2025-02-01",
    endDate: "2025-08-15",
    status: "In Progress",
    remarks: "Survey work in progress.",
  },
  {
    id: "site-3",
    name: "Metro Station Stretch",
    code: "SN-MTR",
    city: "Jaipur",
    fullAddress: "Metro Corridor, Shyam Nagar, Jaipur",
    latitude: 26.902,
    longitude: 75.78,
    supervisor: "Farhan Khan",
    plannedConnections: 620,
    startDate: "2025-03-10",
    endDate: "2025-09-20",
    status: "Not Started",
    remarks: "Awaiting traffic clearance.",
  },
];

export const projectDocuments: ProjectDocument[] = [
  {
    id: "doc-1",
    type: "Tender",
    number: "SN/CGD/2024/17",
    documentName: "Tender Contract Document",
    documentDate: "2024-12-20",
    contractDate: "2024-12-20",
    issueDate: "2024-12-20",
    expiryDate: "2026-12-20",
    amount: "₹ 12.50 Cr",
    category: "Tender",
    fileName: "Tender_SN_CGD_2024_17.pdf",
    remarks: "Tender no. and contract date verified.",
    uploadedOn: "2025-01-10",
    uploadedBy: "Demo Admin",
  },
  {
    id: "doc-2",
    type: "LOA",
    number: "LOA/2025/101",
    documentName: "Letter of Award",
    documentDate: "2025-01-18",
    contractDate: "2025-01-18",
    issueDate: "2025-01-18",
    expiryDate: "2026-01-14",
    amount: "₹ 12.50 Cr",
    category: "LOA",
    fileName: "LOA_2025_101.pdf",
    remarks: "LOA no. and amount captured.",
    uploadedOn: "2025-01-20",
    uploadedBy: "Demo Admin",
  },
  {
    id: "doc-3",
    type: "FOA",
    number: "FOA/2025/167",
    documentName: "Final Order Acceptance",
    documentDate: "2025-01-24",
    contractDate: "2025-01-24",
    issueDate: "2025-01-24",
    expiryDate: "2026-01-14",
    amount: "₹ 12.50 Cr",
    category: "FOA",
    fileName: "FOA_2025_167.pdf",
    remarks: "FOA no. and amount captured.",
    uploadedOn: "2025-01-25",
    uploadedBy: "Demo Admin",
  },
  {
    id: "doc-4",
    type: "EOI",
    number: "EOI/2024/044",
    documentName: "Expression of Interest",
    documentDate: "2024-11-28",
    contractDate: "2024-11-28",
    issueDate: "2024-11-28",
    expiryDate: "2025-11-27",
    amount: "₹ 25.00 L",
    category: "EOI",
    fileName: "EOI_SN_CGD_2024_044.pdf",
    remarks: "EOI no. and amount captured.",
    uploadedOn: "2025-01-12",
    uploadedBy: "Demo Admin",
  },
  {
    id: "doc-5",
    type: "BG",
    number: "BG/2025/331",
    documentName: "Bank Guarantee",
    documentDate: "2025-01-30",
    contractDate: "2025-01-30",
    issueDate: "2025-01-30",
    expiryDate: "2026-01-30",
    amount: "₹ 1.25 Cr",
    category: "BG",
    fileName: "BG_2025_331.pdf",
    remarks: "Performance bank guarantee.",
    uploadedOn: "2025-02-01",
    uploadedBy: "Demo Admin",
  },
  {
    id: "doc-6",
    type: "RO",
    number: "RO/2025/044-1",
    documentName: "Release Order 1",
    documentDate: "2025-02-02",
    contractDate: "2025-02-02",
    issueDate: "2025-02-02",
    expiryDate: "",
    amount: "₹ 48.00 L",
    category: "RO",
    fileName: "RO_2025_044_1.pdf",
    remarks: "RO 1 amount captured.",
    uploadedOn: "2025-02-03",
    uploadedBy: "Demo Admin",
  },
  {
    id: "doc-7",
    type: "RO",
    number: "RO/2025/044-2",
    documentName: "Release Order 2",
    documentDate: "2025-02-15",
    contractDate: "2025-02-15",
    issueDate: "2025-02-15",
    expiryDate: "",
    amount: "₹ 52.00 L",
    category: "RO",
    fileName: "RO_2025_044_2.pdf",
    remarks: "RO 2 amount captured.",
    uploadedOn: "2025-02-16",
    uploadedBy: "Demo Admin",
  },
  {
    id: "doc-8",
    type: "Statutory",
    number: "STAT/SN/2025/01",
    documentName: "GST Registration Certificate",
    documentDate: "2025-01-05",
    contractDate: "2025-01-05",
    issueDate: "2025-01-05",
    expiryDate: "",
    amount: "-",
    category: "Statutory",
    fileName: "GST_Reg_Certificate.pdf",
    remarks: "Statutory document 1.",
    uploadedOn: "2025-02-05",
    uploadedBy: "Demo Admin",
  },
];
export const assignedUsers: AssignedUser[] = [
  {
    id: "user-1",
    name: "Amit Sharma",
    role: "Project Manager",
    siteArea: "All Sites",
    assignmentDate: "2025-01-15",
    status: "Active",
  },
  {
    id: "user-2",
    name: "Ramesh Kumar",
    role: "Site Supervisor",
    siteArea: "Shyam Nagar Block A",
    assignmentDate: "2025-01-18",
    status: "Active",
  },
  {
    id: "user-3",
    name: "Kavita Joshi",
    role: "Survey Lead",
    siteArea: "Shyam Nagar Block B",
    assignmentDate: "2025-02-01",
    status: "In Progress",
  },
  {
    id: "user-4",
    name: "Neha Verma",
    role: "Billing Executive",
    siteArea: "Commercial",
    assignmentDate: "2025-02-05",
    status: "Active",
  },
];

export const projectActivity: ActivityItem[] = [
  {
    id: "act-1",
    title: "Project created",
    description: "Contract and baseline project information were added.",
    actor: "Demo Admin",
    dateTime: "2025-01-15 10:20",
    relatedRecord: "CGD-SN-2025",
  },
  {
    id: "act-2",
    title: "Site added",
    description: "Shyam Nagar Block A was assigned to field operations.",
    actor: "Amit Sharma",
    dateTime: "2025-01-18 14:05",
    relatedRecord: "SN-A",
  },
  {
    id: "act-3",
    title: "Document uploaded",
    description: "LOA document uploaded by Demo Admin.",
    actor: "Demo Admin",
    dateTime: "2025-01-20 12:30",
    relatedRecord: "LOA/2025/101",
  },
  {
    id: "act-4",
    title: "Status updated",
    description: "Project moved from Draft to In Progress.",
    actor: "Amit Sharma",
    dateTime: "2025-01-22 09:45",
    relatedRecord: "Project Status",
  },
];

export function getProjectById(id: string) {
  return projects.find((project) => project.id === id) ?? projects[0];
}

export const cityOptions = Array.from(new Set(projects.map((project) => project.city)));
export const contractorOptions = Array.from(
  new Set(projects.map((project) => project.contractor)),
);
