export const tableDensity = {
  rowHeight: "h-9",
  headerText: "text-[11px]",
  bodyText: "text-xs",
  cellPaddingX: "px-2.5",
  cellPaddingY: "py-1.5",
  checkboxSize: "size-3.5",
  pagerButtonHeight: "h-7",
  headerBg: "bg-surface-muted",
  headerText2: "text-foreground/75",
  pinnedBodyBg: "bg-surface",
  cellDividerColor: "border-border",
  rowBottomBorder: "border-b-border",
  pinnedRegionDivider: "border-border",
  hoverBg: "hover:bg-surface-hover",
} as const;
