import { AuthUser } from '@/types/auth'

export const MOCK_USERS: (AuthUser & { password: string })[] = [
  {
    id: '1',
    username: 'superadmin',
    password: 'admin123',
    fullName: 'Super Admin',
    role: 'super_admin',
    assignedProjects: [],
    isActive: true,
    lastLogin: '2025-05-21T10:30:00Z',
  },
  {
    id: '2',
    username: 'admin',
    password: 'admin123',
    fullName: 'Demo Admin',
    role: 'admin',
    assignedProjects: ['proj-1', 'proj-2'],
    assignedCity: 'Jaipur',
    isActive: true,
    lastLogin: '2025-05-21T09:00:00Z',
  },
  {
    id: '3',
    username: 'pm',
    password: 'admin123',
    fullName: 'Rajesh Kumar',
    role: 'project_manager',
    assignedProjects: ['proj-1'],
    assignedCity: 'Jaipur',
    isActive: true,
    lastLogin: '2025-05-20T14:00:00Z',
  },
  {
    id: '4',
    username: 'accounts',
    password: 'admin123',
    fullName: 'Pooja Sharma',
    role: 'accounts',
    assignedProjects: ['proj-1', 'proj-2'],
    isActive: true,
    lastLogin: '2025-05-19T11:00:00Z',
  },
  {
    id: '5',
    username: 'store',
    password: 'admin123',
    fullName: 'Amit Verma',
    role: 'store',
    assignedProjects: ['proj-1'],
    isActive: true,
    lastLogin: '2025-05-18T09:30:00Z',
  },
  {
    id: '6',
    username: 'supervisor',
    password: 'admin123',
    fullName: 'Sandeep Meena',
    role: 'supervisor',
    assignedProjects: ['proj-1'],
    assignedCity: 'Jaipur',
    isActive: true,
    lastLogin: '2025-05-21T08:00:00Z',
  },
  {
    id: '7',
    username: 'viewer',
    password: 'admin123',
    fullName: 'Client Viewer',
    role: 'viewer',
    assignedProjects: ['proj-1'],
    isActive: true,
    lastLogin: '2025-05-15T10:00:00Z',
  },
]
