import type {
  Customer,
  CustomerActivity,
  CustomerDocument,
  CustomerGiDetails,
  CustomerWorkStageRecord,
  ImportPreviewRow,
} from "../types/customer.types";

export const connectionTypeOptions = ["Domestic", "Commercial", "Industrial"] as const;

export const customerStageOptions = [
  "Lead",
  "Survey",
  "Plumbing / GI",
  "GC",
  "Commissioning",
  "Conversion",
  "Completed",
] as const;

export const customerStatusOptions = [
  "Draft",
  "Active",
  "On Hold",
  "Completed",
  "Archived",
] as const;

export const customers: Customer[] = [
  {
    id: "cust-001",
    name: "Rajesh Kumar",
    mobileNumber: "9876543210",
    fullAddress: "42, Shyam Nagar Block A, Jaipur",
    projectId: "shyam-nagar-cgd",
    projectName: "Shyam Nagar CGD Project",
    siteArea: "Shyam Nagar Block A",
    city: "Jaipur",
    latitude: "26.8951",
    longitude: "75.7684",
    bpTrNumber: "BP-100245",
    connectionType: "Domestic",
    houseType: "Independent House",
    scheme: "Standard PNG",
    paymentStatus: "Approved",
    paymentMode: "UPI",
    initialAmount: "3500",
    supervisor: "Ramesh Kumar",
    plumberGroup: "Group A",
    fieldExecutive: "Vikas Saini",
    meterNumber: "MTR-77881",
    meterType: "Smart Meter",
    regulatorNumber: "REG-2219",
    regulatorPressure: "21 mbar",
    currentStage: "Commissioning",
    status: "Active",
    createdDate: "2025-01-24",
    surveyDate: "2025-01-28",
    installationDate: "2025-02-08",
    testingDate: "2025-02-12",
    commissioningDate: "2025-02-15",
    conversionDate: "",
    meterReading: "128.4 SCM",
    nonConversionRemarks: "Customer requested weekend conversion.",
    giBillDone: true,
    gcBillDone: true,
    conversionBillDone: false,
  },
  {
    id: "cust-002",
    name: "Meena Sharma",
    mobileNumber: "9823411122",
    fullAddress: "11, New Sanganer Road, Shyam Nagar, Jaipur",
    projectId: "shyam-nagar-cgd",
    projectName: "Shyam Nagar CGD Project",
    siteArea: "Shyam Nagar Block B",
    city: "Jaipur",
    latitude: "26.8877",
    longitude: "75.7592",
    bpTrNumber: "TR-553901",
    connectionType: "Domestic",
    houseType: "Apartment",
    scheme: "Deposit Waiver",
    paymentStatus: "Pending",
    paymentMode: "Cash",
    initialAmount: "1500",
    supervisor: "Kavita Joshi",
    plumberGroup: "Group B",
    fieldExecutive: "Amit Rathore",
    meterNumber: "MTR-77892",
    meterType: "Mechanical",
    regulatorNumber: "REG-2231",
    regulatorPressure: "21 mbar",
    currentStage: "GC",
    status: "Active",
    createdDate: "2025-02-02",
    surveyDate: "2025-02-04",
    installationDate: "2025-02-15",
    testingDate: "",
    commissioningDate: "",
    conversionDate: "",
    meterReading: "0 SCM",
    nonConversionRemarks: "",
    giBillDone: true,
    gcBillDone: false,
    conversionBillDone: false,
  },
  {
    id: "cust-003",
    name: "Green Mart Store",
    mobileNumber: "9810012200",
    fullAddress: "Shop 8, Green City Phase 1, Indore",
    projectId: "green-city-phase-1",
    projectName: "Green City Phase 1",
    siteArea: "Commercial Block",
    city: "Indore",
    latitude: "22.7196",
    longitude: "75.8577",
    bpTrNumber: "BP-220118",
    connectionType: "Commercial",
    houseType: "Retail Shop",
    scheme: "Commercial Plan",
    paymentStatus: "Approved",
    paymentMode: "Bank Transfer",
    initialAmount: "12000",
    supervisor: "Neha Verma",
    plumberGroup: "Commercial Team",
    fieldExecutive: "Pawan Jain",
    meterNumber: "MTR-88021",
    meterType: "Smart Meter",
    regulatorNumber: "REG-3341",
    regulatorPressure: "100 mbar",
    currentStage: "Conversion",
    status: "Active",
    createdDate: "2025-02-11",
    surveyDate: "2025-02-13",
    installationDate: "2025-02-22",
    testingDate: "2025-02-26",
    commissioningDate: "2025-03-01",
    conversionDate: "2025-03-04",
    meterReading: "546.2 SCM",
    nonConversionRemarks: "",
    giBillDone: true,
    gcBillDone: true,
    conversionBillDone: true,
  },
  {
    id: "cust-004",
    name: "Rafiq Khan",
    mobileNumber: "9901122334",
    fullAddress: "7, Sunrise Enclave, Udaipur",
    projectId: "sunrise-enclave-cgd",
    projectName: "Sunrise Enclave CGD",
    siteArea: "Sunrise Enclave",
    city: "Udaipur",
    latitude: "24.5854",
    longitude: "73.7125",
    bpTrNumber: "TR-783441",
    connectionType: "Domestic",
    houseType: "Villa",
    scheme: "Standard PNG",
    paymentStatus: "In Review",
    paymentMode: "Cheque",
    initialAmount: "3500",
    supervisor: "Priya Nair",
    plumberGroup: "Group C",
    fieldExecutive: "Sameer Ali",
    meterNumber: "",
    meterType: "",
    regulatorNumber: "",
    regulatorPressure: "",
    currentStage: "Survey",
    status: "On Hold",
    createdDate: "2025-03-02",
    surveyDate: "2025-03-04",
    installationDate: "",
    testingDate: "",
    commissioningDate: "",
    conversionDate: "",
    meterReading: "",
    nonConversionRemarks: "Address verification pending.",
    giBillDone: false,
    gcBillDone: false,
    conversionBillDone: false,
  },
];

export const customerWorkStages: CustomerWorkStageRecord[] = [
  {
    id: "stage-1",
    stage: "Survey",
    status: "Completed",
    date: "2025-01-28",
    updatedBy: "Vikas Saini",
    relatedRecord: "Survey #SUR-100245",
    href: "/surveys?customerId=cust-001",
  },
  {
    id: "stage-2",
    stage: "Workable",
    status: "Workable",
    date: "2025-01-29",
    updatedBy: "Ramesh Kumar",
    relatedRecord: "Workable Check",
    href: "/work-progress?customerId=cust-001",
  },
  {
    id: "stage-3",
    stage: "Plumbing / GI",
    status: "Completed",
    date: "2025-02-08",
    updatedBy: "Group A",
    relatedRecord: "GI Report #GI-245",
    href: "/customers/cust-001/gi-details",
  },
  {
    id: "stage-4",
    stage: "GC",
    status: "Submitted",
    date: "2025-02-12",
    updatedBy: "Vikas Saini",
    relatedRecord: "GC Upload #GC-245",
    href: "/gc-uploads?customerId=cust-001",
  },
  {
    id: "stage-5",
    stage: "Commissioning",
    status: "Completed",
    date: "2025-02-15",
    updatedBy: "Ramesh Kumar",
    relatedRecord: "Commissioning #COM-245",
    href: "/pre-commissioning?customerId=cust-001",
  },
  {
    id: "stage-6",
    stage: "Conversion",
    status: "Pending",
    date: "2025-02-17",
    updatedBy: "Demo Admin",
    relatedRecord: "Conversion Pending",
    href: "/work-progress?customerId=cust-001",
  },
];

export const customerGiDetails: CustomerGiDetails = {
  customerId: "cust-001",
  inlet: "Kitchen wall inlet",
  outlet: "Meter outlet to appliance point",
  totalGi: "18.5 m",
  extraGi: "2.5 m",
  pipeSizes: "15MM, 20MM",
  valves: "2",
  regulators: "1",
  clamps: "14",
  elbows: "8",
  tees: "2",
  nipples: "6",
  installationDate: "2025-02-08",
  photos: ["Inlet point", "Meter wall", "Kitchen outlet"],
  relatedReport: "GI Report #GI-245",
};

export const customerDocuments: CustomerDocument[] = [
  {
    id: "doc-1",
    title: "Survey photos",
    category: "Survey",
    fileName: "survey_rajesh_kumar.zip",
    uploadedOn: "2025-01-28",
    status: "Approved",
  },
  {
    id: "doc-2",
    title: "GC image / PDF",
    category: "GC",
    fileName: "gc_bp_100245.pdf",
    uploadedOn: "2025-02-12",
    status: "Submitted",
  },
  {
    id: "doc-3",
    title: "Pressure observation report",
    category: "Testing",
    fileName: "pressure_bp_100245.pdf",
    uploadedOn: "2025-02-14",
    status: "In Review",
  },
  {
    id: "doc-4",
    title: "JMR upload",
    category: "JMR",
    fileName: "jmr_bp_100245.pdf",
    uploadedOn: "2025-02-16",
    status: "Pending",
  },
];

export const customerActivity: CustomerActivity[] = [
  {
    id: "act-1",
    title: "Customer created",
    description: "Customer master record was created from field onboarding.",
    actor: "Demo Admin",
    dateTime: "2025-01-24 10:15",
    relatedRecord: "BP-100245",
  },
  {
    id: "act-2",
    title: "Survey submitted",
    description: "Survey photos and workable status were submitted.",
    actor: "Vikas Saini",
    dateTime: "2025-01-28 16:40",
    relatedRecord: "Survey",
  },
  {
    id: "act-3",
    title: "Meter assigned",
    description: "Meter MTR-77881 and regulator REG-2219 were assigned.",
    actor: "Ramesh Kumar",
    dateTime: "2025-02-08 12:05",
    relatedRecord: "MTR-77881",
  },
  {
    id: "act-4",
    title: "GC uploaded",
    description: "GC image and PDF were uploaded for approval.",
    actor: "Vikas Saini",
    dateTime: "2025-02-12 18:10",
    relatedRecord: "GC Upload",
  },
  {
    id: "act-5",
    title: "Approval history",
    description: "Pressure observation report moved to review.",
    actor: "Demo Admin",
    dateTime: "2025-02-14 11:35",
    relatedRecord: "Pressure Report",
  },
];

export const importPreviewRows: ImportPreviewRow[] = [
  {
    id: "row-1",
    rowNumber: 2,
    customerName: "Anil Gupta",
    mobileNumber: "9876500011",
    bpTrNumber: "BP-991002",
    project: "Shyam Nagar CGD Project",
    area: "Shyam Nagar Block A",
    status: "Valid",
    errors: [],
  },
  {
    id: "row-2",
    rowNumber: 3,
    customerName: "Sunita Jain",
    mobileNumber: "98000",
    bpTrNumber: "",
    project: "Green City Phase 1",
    area: "Commercial Block",
    status: "Error",
    errors: ["Mobile number must be 10 digits", "BP / TR Number is required"],
  },
  {
    id: "row-3",
    rowNumber: 4,
    customerName: "Hotel Midtown",
    mobileNumber: "9811100220",
    bpTrNumber: "BP-991003",
    project: "Green City Phase 1",
    area: "Commercial Block",
    status: "Valid",
    errors: [],
  },
];

export function getCustomerById(id: string) {
  return customers.find((customer) => customer.id === id) ?? customers[0];
}

export const projectOptions = Array.from(
  new Map(customers.map((customer) => [customer.projectId, customer.projectName])),
).map(([value, label]) => ({ value, label }));

export const cityAreaOptions = Array.from(
  new Set(customers.map((customer) => `${customer.city} / ${customer.siteArea}`)),
);

export const siteOptionsByProject = customers.reduce<Record<string, string[]>>(
  (options, customer) => {
    options[customer.projectId] = Array.from(
      new Set([...(options[customer.projectId] ?? []), customer.siteArea]),
    );
    return options;
  },
  {},
);

export const assignmentOptionsBySite = customers.reduce<
  Record<string, { supervisors: string[]; plumbers: string[]; fieldExecutives: string[] }>
>((options, customer) => {
  const current = options[customer.siteArea] ?? {
    supervisors: [],
    plumbers: [],
    fieldExecutives: [],
  };
  options[customer.siteArea] = {
    supervisors: Array.from(new Set([...current.supervisors, customer.supervisor])),
    plumbers: Array.from(new Set([...current.plumbers, customer.plumberGroup])),
    fieldExecutives: Array.from(
      new Set([...current.fieldExecutives, customer.fieldExecutive]),
    ),
  };
  return options;
}, {});
