import {
  emptyBillingCompletion,
  emptyCommissioningConversion,
  emptyCustomerConnection,
  emptyCustomerSurvey,
  emptyLmcPipelineWork,
  emptyMdpeFittings,
} from "./customers.service";
import type { Customer } from "../types/customer.types";

/**
 * Static placeholder data still consumed by report-templates.service.ts until that feature is
 * wired to the real backend too - see INTEGRATION_PLAN.md. The real customers screens use
 * customers.service.ts's customersApi instead.
 */
export const customers: Customer[] = [
  {
    id: "cust-001",
    status: "Active",
    projectId: "shyam-nagar-cgd",
    siteId: "site-1",
    projectName: "Shyam Nagar CGD Project",
    siteArea: "Shyam Nagar Block A",
    city: "Jaipur",
    createdDate: "2025-01-24",
    customerConnection: {
      ...emptyCustomerConnection,
      reportNoGi: "GI-100245",
      reportNoGc: "GC-100245",
      reportNoConversion: "CONV-100245",
      trBpNo: "BP-100245",
      mobileNo: "9876543210",
      customerName: "Rajesh Kumar",
      fullAddress: "42, Shyam Nagar Block A, Jaipur",
      scheme: "Standard PNG",
      plumberName: "Group A",
      supervisorName: "Ramesh Kumar",
      jobCardDone: "Yes",
      connectionType: "Domestic",
      houseType: "Independent House",
    },
    giMeasurements: {
      tfToRegulator: "1.5",
      inlet: "3.2",
      outlet: "2.6",
      totalGiPipeHalfInch: "18.5",
      giPipeThreeQuarterInch: "2",
      giPipeOneInch: "0",
      giPipeOneAndHalfInch: "0",
      giPipeTwoInch: "0",
    },
    valvesRegulators: {
      isolationValveHalfInch: "1",
      isolationValveThreeQuarterInch: "0",
      isolationValveOneInch: "0",
      isolationValveOneAndHalfInch: "0",
      isolationValveTwoInch: "0",
      applianceValveHalfInch: "1",
      regulator6BarTo100Mbar: "0",
      regulator6BarTo21Mbar: "1",
      regulator100MbarTo21Mbar: "0",
      warningPlate: "1",
    },
    fittingsAccessories: {
      clampHalfInch: "12",
      clamp3InchToHalfInch: "0",
      elbowHalfInch: "6",
      mfElbowHalfInch: "0",
      socketHalfInch: "0",
      teeHalfInch: "1",
      nipple2Inch: "0",
      nipple3Inch: "0",
      nipple4Inch: "0",
      reducerElbowThreeQuarterToHalfInch: "0",
      threeQuarterInchTo3Inch: "0",
      unionHalfInch: "1",
      plugHalfInch: "1",
      fittingsOneAndHalfInchQuantity: "0",
      fittingsTwoInchQuantity: "0",
      extraGiAbove10Metres: "8.5",
    },
    lmcPipelineWork: {
      ...emptyLmcPipelineWork,
      fourMetresUnderGc: "4",
      fourMetresAboveGc: "2",
      tfHalfInch: "1",
      pcc: "3",
      paverBlocks: "6",
      malua: "1",
    },
    mdpeFittings: emptyMdpeFittings,
    commissioningConversion: {
      ...emptyCommissioningConversion,
      meterNo: "MTR-77881",
      installationDate: "2025-02-08",
      commissioningDate: "2025-02-15",
      regulatorPressure: "21 mbar",
      regulatorNo: "REG-2219",
      meterType: "Smart Meter",
      meterReading: "128.4 SCM",
    },
    billingCompletion: {
      ...emptyBillingCompletion,
      paymentStatus: "Approved",
      paymentMode: "UPI",
      initialAmount: "3500",
      jmrDone: true,
      jmrSubmittedInPbg: true,
      giBillDone: true,
      gcBillDone: true,
      remark: "Conversion bill pending.",
    },
    survey: {
      ...emptyCustomerSurvey,
      id: "survey-001",
      surveyId: "SUR-100245",
      surveyDate: "2025-01-28",
      assignedSurveyor: "Vikas Saini",
      workableStatus: "Workable",
      approvalStatus: "Submitted",
    },
    media: [],
    documents: [],
  },
  {
    id: "cust-002",
    status: "Pending",
    projectId: "green-city-phase-1",
    siteId: "site-2",
    projectName: "Green City Phase 1",
    siteArea: "Green City Township",
    city: "Indore",
    createdDate: "2025-02-01",
    customerConnection: {
      ...emptyCustomerConnection,
      trBpNo: "BP-100260",
      mobileNo: "9812345678",
      customerName: "Meena Sharma",
      fullAddress: "Green City Township, Indore",
      connectionType: "Domestic",
    },
    giMeasurements: {
      tfToRegulator: "",
      inlet: "",
      outlet: "",
      totalGiPipeHalfInch: "",
      giPipeThreeQuarterInch: "",
      giPipeOneInch: "",
      giPipeOneAndHalfInch: "",
      giPipeTwoInch: "",
    },
    valvesRegulators: {
      isolationValveHalfInch: "",
      isolationValveThreeQuarterInch: "",
      isolationValveOneInch: "",
      isolationValveOneAndHalfInch: "",
      isolationValveTwoInch: "",
      applianceValveHalfInch: "",
      regulator6BarTo100Mbar: "",
      regulator6BarTo21Mbar: "",
      regulator100MbarTo21Mbar: "",
      warningPlate: "",
    },
    fittingsAccessories: {
      clampHalfInch: "",
      clamp3InchToHalfInch: "",
      elbowHalfInch: "",
      mfElbowHalfInch: "",
      socketHalfInch: "",
      teeHalfInch: "",
      nipple2Inch: "",
      nipple3Inch: "",
      nipple4Inch: "",
      reducerElbowThreeQuarterToHalfInch: "",
      threeQuarterInchTo3Inch: "",
      unionHalfInch: "",
      plugHalfInch: "",
      fittingsOneAndHalfInchQuantity: "",
      fittingsTwoInchQuantity: "",
      extraGiAbove10Metres: "",
    },
    lmcPipelineWork: emptyLmcPipelineWork,
    mdpeFittings: emptyMdpeFittings,
    commissioningConversion: emptyCommissioningConversion,
    billingCompletion: {
      ...emptyBillingCompletion,
      paymentStatus: "Pending",
    },
    survey: {
      ...emptyCustomerSurvey,
      id: "survey-002",
      surveyId: "SUR-100260",
      surveyDate: "2025-02-05",
      assignedSurveyor: "Vikas Saini",
      workableStatus: "Partially Workable",
      approvalStatus: "Sent Back",
    },
    media: [],
    documents: [],
  },
];

export function getCustomerById(id: string) {
  return customers.find((customer) => customer.id === id) ?? customers[0];
}
